############# English navigation ##############

# main menu
[[main]]
name = "Látás"
url = "/latas/"
weight = 1

[[main]]
name = "Április 4."
url = "/aprilis-4/"
weight = 2

[[main]]
name = "GYIK"
url = "/gyik/"
weight = 3

[[main]]
name = "Kapcsolat"
pageRef = "/contact"
weight = 4



# footer menu
[[footer_01]]
name = "Látás – Mohács 500"
url = "/latas"
weight = 1

[[footer_01]]
name = "Április 4."
url = "/aprilis-4"
weight = 2

[[footer_01]]
name = "GYIK"
url = "/gyik"
weight = 3

[[footer_02]]
name = "Kapcsolat"
url = "/contact"
weight = 1

[[footer_02]]
name = "Alabástrom Projekt"
url = "https://www.alabastromprojekt.hu"
weight = 2
